#!/bin/bash
#Author by @aliasmee
#Time 2018-03-6 01:10

if [ -z "$O" ]; then 
    O=vpn
fi

if [ -z "$CN" ]; then 
    CN=$HOST_IP
fi


cd /data/key_files
if [ "`ls -A`" = "" ]; then
    # Create certificate
    ipsec pki --gen --outform pem > ca.pem
    ipsec pki --self --in ca.pem --dn "C=cn, O=$O, CN=$CN" --ca --lifetime 3650 --outform pem >ca.cert.pem
    ipsec pki --gen --outform pem > server.pem
    ipsec pki --gen --outform pem > client.pem
    ipsec pki --pub --in server.pem | ipsec pki --issue --lifetime 1200 --cacert ca.cert.pem --cakey ca.pem --dn "C=cn, O=$O, CN=$HOST_IP" --san="$HOST_IP" --flag serverAuth --flag ikeIntermediate --outform pem > server.cert.pem
    ipsec pki --pub --in client.pem | ipsec pki --issue --cacert ca.cert.pem --cakey ca.pem --dn "C=cn, O=$O, CN=vpn client" --outform pem > client.cert.pem

    # Copy certificate to ipsec dir
    \cp ca.cert.pem /usr/local/etc/ipsec.d/cacerts/
    \cp server.cert.pem /usr/local/etc/ipsec.d/certs/
    \cp server.pem /usr/local/etc/ipsec.d/private/
    \cp client.cert.pem /usr/local/etc/ipsec.d/certs/
    \cp client.pem  /usr/local/etc/ipsec.d/private/

    # View the certificate contents and save file
    echo "Below the horizontal line is the content of the certificate. Copy the content to a file in the .cert suffix format. Such as: vpn.cert"
    echo "______________________________________________________________"
    cat /data/key_files/ca.cert.pem
else
    echo "/data/key_files is not empty, using provided certificate"
    \cp *.crt /usr/local/etc/ipsec.d/cacerts/ca.cert.pem
    \cp *.cer /usr/local/etc/ipsec.d/certs/server.cert.pem
    \cp *.key /usr/local/etc/ipsec.d/private/server.pem
fi


# Enable system forward
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv4.ip_no_pmtu_disc=1

# Load iptables rules
iptables-restore < /etc/sysconfig/iptables

# Custom connection VPN username password
sed -i "$ a $VPNUSER %any : EAP '$VPNPASS'"  /usr/local/etc/ipsec.secrets

# Reboot ipsec vpn loading cert
supervisorctl restart ipsec

